Repository codeit-maso/Rolling, pull requests merged in 2025-05, with the labels that each got.

#128 🐛 fix: 페이지 로드중일때 메시지 삭제
  src/pages/Recipient/Recipient.jsx
Labels: 🐛 버그 수정

#129 ✨ feat: 이미지 업로드 로딩바 구현
  src/api/postUpload.js
  src/components/BackgroundCard/BackgroundCard.jsx
  src/components/BackgroundCard/BackgroundCard.module.scss
  src/components/UserProfileSelector/UserProfileSelector.jsx
  src/components/UserProfileSelector/UserProfileSelector.module.scss
  src/components/common/UploadProgressBar.jsx
  src/components/common/UploadProgressBar.module.scss
  src/pages/CreateRecipient/CreateRecipient.jsx
  src/pages/MessageForm/MessageForm.jsx
Labels: ✨ 기능 추가/구현

#131 ✨ feat: 이모지 카운트 포맷팅 및 프로필 +N 카운트 제한 기능 추가 / 코드 스플리팅 적용
  src/App.jsx
  src/components/recipient/HeaderService/HeaderService.jsx
  src/utils/numberFormat.js
Labels: ✨ 기능 추가/구현

#135 📝 docs: README.md 프로젝트 소개 페이지 수정
  README.md
Labels: 📝 문서 작업
