Repository codeit-maso/Rolling, pull requests merged in 2025-04, with the labels that each got.

#16 공통 컴포넌트 구현 - Card, Badge
  .gitattributes
  .prettierrc
  index.html
  public/.gitkeep
  src/App.jsx
  src/api/.gitkeep
  src/assets/images/.gitkeep
  src/assets/images/delete.svg
  src/assets/images/plus.png
  src/assets/styles/.gitkeep
  src/base.scss
  src/components/common/.gitkeep
  src/components/common/Badge/Badge.jsx
  src/components/common/Badge/Badge.module.scss
  src/components/common/Card/Card.jsx
  src/components/common/Card/Card.module.scss
  src/components/layout/.gitkeep
  src/context/.gitkeep
  src/hooks/.gitkeep
  src/pages/.gitkeep
  src/store/.gitkeep
  src/utils/.gitkeep
Labels: ✨ 기능 추가/구현, 🎨 UI/스타일 관련

#17 🔧 chore: GitHub Actions 워크플로우 추가 - 포크 자동 동기화
  .github/workflows/sync-fork.yml
Labels: 🔧 설정/환경 변경, 🚀 배포 관련

#28 🔧 chore: 워크플로우 추가하여 개인 포크 자동 동기화 구현 - SSH 키 인증 대체
  .github/workflows/sync-fork.yml
Labels: 🐛 버그 수정, 🔧 설정/환경 변경, 🚀 배포 관련

#33 ✨feat: 프로필 이미지 선택 구현 및 Axios 모듈화 완료feat: 프로필 이미지 선택 구현 및 Axios 모듈화 완료
  eslint.config.js
  src/App.jsx
  src/api/api.js
  src/api/fetchProfileImages.js.js
  src/components/common/Button.jsx
  src/components/user-profile/UserProFileSelector.jsx
  src/components/user-profile/UserProFileSelector.module.scss
  src/constants/image.js
Labels: ✨ 기능 추가/구현

#35 롤링페이지 생성 페이지 구현 및 라우팅 설정
  src/App.jsx
  src/api/getBackgroundImage.js
  src/api/postRecipient.js
  src/assets/images/checked.svg
  src/components/Badge/Badge.jsx
  src/components/Badge/Badge.module.scss
  src/components/Card/Card.jsx
  src/components/Card/Card.module.scss
  src/pages/CreateRecipient/CreateRecipient.jsx
  src/pages/CreateRecipient/CreateRecipient.module.scss
  src/pages/MessageForm/MessageForm.jsx
  src/pages/Recipient/Recipient.jsx
  src/pages/RecipientList/RecipientList.jsx
Labels: ✨ 기능 추가/구현, 🎨 UI/스타일 관련, 📁 폴더구조 변경

#36 ✨ feat: 리스트 페이지의 캐러셀 및 카드 구현, + variable.scss 폰트 속성 추가
  src/App.jsx
  src/api/getRecipients.js
  src/assets/images/next.svg
  src/assets/styles/base.scss
  src/assets/styles/variables.scss
  src/pages/RecipientList/Carousel.jsx
  src/pages/RecipientList/Carousel.module.scss
  src/pages/RecipientList/RecentMessages.jsx
  src/pages/RecipientList/RecentMessages.module.scss
  src/pages/RecipientList/RecipientCard.jsx
  src/pages/RecipientList/RecipientCard.module.scss
  src/pages/RecipientList/RecipientList.jsx
  src/pages/RecipientList/RecipientList.module.scss
  src/pages/RecipientList/TopReactions.jsx
  src/pages/RecipientList/TopReactions.module.scss
Labels: ✨ 기능 추가/구현

#44 ✨feat: 텍스트 에디터 구현
  package-lock.json
  package.json
  src/api/api.js
  src/api/fetchProfileImages.js
  src/api/fetchProfileImages.js.js
  src/api/getBackgroundImage.js
  src/api/getRecipients.js
  src/api/postRecipient.js
  src/assets/images/arrow.svg
  src/components/Editor/Editor.jsx
  src/components/Editor/Editor.module.scss
  src/components/RelationshipSelect/RelationshipSelect.jsx
  src/components/RelationshipSelect/RelationshipSelect.module.scss
  src/components/UserProfileSelector/UserProfileSelector.jsx
  src/components/UserProfileSelector/UserProfileSelector.module.scss
  src/hooks/useDetectClose.jsx
Labels: ✨ 기능 추가/구현

#49 ✨ feat: HeaderService 컴포넌트 구현
  src/api/fetchReactions.js
  src/api/fetchRecipient.js
  src/assets/images/chevron-down.svg
  src/assets/images/emoji-add.svg
  src/assets/images/share.svg
  src/components/recipient/HeaderService/HeaderService.jsx
  src/components/recipient/HeaderService/HeaderService.module.scss
  src/pages/Recipient/Recipient.jsx
  src/pages/RecipientList/RecipientCard.jsx
Labels: ✨ 기능 추가/구현, 🎨 UI/스타일 관련

#58 🐛 fix: 팀ID 환경변수 적용 및 Vercel 배포 라우팅 설정 추가
  src/api/getRecipients.js
  vercel.json
Labels: 🐛 버그 수정, 🔧 설정/환경 변경, 🚀 배포 관련

#60 ✨ feat: 폰트 드롭다운 구현 및 메세지 페이지 구현
  index.html
  src/api/createMessage.js
  src/components/Editor/Editor.jsx
  src/components/FontSelect/FontSelect.jsx
  src/components/FontSelect/FontSelect.module.scss
  src/pages/MessageForm/MessageForm.jsx
  src/pages/MessageForm/MessageForm.module.scss
Labels: ✨ 기능 추가/구현

#62 ✨ feat: /post/id 페이지 구현 - 작성한 메시지 카드로 보여주기, 무한스크롤 구현
  package-lock.json
  package.json
  src/api/getMessages.js
  src/api/getRecipient.js
  src/components/Badge/Badge.jsx
  src/components/Card/Card.jsx
  src/components/Card/Card.module.scss
  src/pages/Home/Home.jsx
  src/pages/MessageForm/MessageForm.jsx
  src/pages/Recipient/Recipient.jsx
  src/pages/Recipient/Recipient.module.scss
Labels: ✨ 기능 추가/구현

#65 ✨ feat: 메시지 삭제, 페이지 삭제, 모달창 구현
  index.html
  src/api/deleteMessage.js
  src/api/deleteRecipient.js
  src/components/Card/Card.jsx
  src/components/Card/Card.module.scss
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.module.scss
  src/components/common/Button.module.scss
  src/pages/Recipient/Recipient.jsx
  src/pages/Recipient/Recipient.module.scss
Labels: ✨ 기능 추가/구현

#68 ✨ feat: 이모지 리액션, 카카오톡 공유, 클립보드 기능 구현
  src/api/emojiReactions.js
  src/api/fetchReactions.js
  src/api/fetchRecipient.js
  src/assets/images/close.svg
  src/assets/images/success.svg
  src/components/common/Toast/Toast.jsx
  src/components/common/Toast/Toast.module.scss
  src/components/recipient/HeaderService/HeaderService.jsx
  src/components/recipient/HeaderService/HeaderService.module.scss
  src/components/recipient/HeaderService/Share/ShareButton.jsx
  src/components/recipient/HeaderService/Share/ShareButton.module.scss
  src/pages/Recipient/Recipient.jsx
  src/utils/share.js
Labels: ✨ 기능 추가/구현, 🎨 UI/스타일 관련, 📁 폴더구조 변경

#74 🎨style: 메인 페이지 및 공통 컴포넌트 반응현 구현
  src/api/getProfileImages.js
  src/api/postMessage.js
  src/assets/images/logo.svg
  src/components/Editor/Editor.jsx
  src/components/Editor/Editor.module.scss
  src/components/FontSelect/FontSelect.jsx
  src/components/FontSelect/FontSelect.module.scss
  src/components/RelationshipSelect/RelationshipSelect.jsx
  src/components/RelationshipSelect/RelationshipSelect.module.scss
  src/components/UserProfileSelector/UserProfileSelector.jsx
  src/components/UserProfileSelector/UserProfileSelector.module.scss
  src/components/common/Button.module.scss
  src/components/common/FormInput.jsx
  src/components/common/FormInput.module.scss
  src/pages/CreateRecipient/CreateRecipient.jsx
  src/pages/Home/Home.jsx
  src/pages/MessageForm/MessageForm.jsx
  src/pages/MessageForm/MessageForm.module.scss
  src/pages/RecipientList/RecipientList.module.scss
Labels: 🎨 UI/스타일 관련, ♻️ 리팩토링

#72 ✨ feat: 모달 스크롤바 구현 및 반응형 구현
  src/assets/styles/variables.scss
  src/components/Card/Card.jsx
  src/components/Card/Card.module.scss
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.module.scss
  src/components/common/Button.module.scss
  src/components/common/FormInput.module.scss
  src/components/layout/Header/Header.jsx
  src/pages/CreateRecipient/CreateRecipient.jsx
  src/pages/CreateRecipient/CreateRecipient.module.scss
  src/pages/Recipient/Recipient.jsx
  src/pages/Recipient/Recipient.module.scss
Labels: ✨ 기능 추가/구현, 🎨 UI/스타일 관련

#76 ✨feat: 메타 태그 추가 및 미리보기 이미지 추가
  index.html
  src/assets/images/rolling-meta.png
  src/components/common/Button.module.scss
  src/components/common/FormInput.jsx
  src/components/layout/Header/Header.jsx
  src/pages/CreateRecipient/CreateRecipient.jsx
  src/pages/MessageForm/MessageForm.jsx
Labels: ✨ 기능 추가/구현, ♻️ 리팩토링

#82 🎨style: 버튼 및 유저 프로필 전환 효과 추가
  src/components/Card/Card.module.scss
  src/components/UserProfileSelector/UserProfileSelector.module.scss
  src/components/common/Button.module.scss
  src/pages/CreateRecipient/CreateRecipient.jsx
  src/pages/CreateRecipient/CreateRecipient.module.scss
  src/pages/MessageForm/MessageForm.jsx
  src/pages/MessageForm/MessageForm.module.scss
Labels: 🎨 UI/스타일 관련, ♻️ 리팩토링

#84 ✨feat: 이미지 업로드 구현 및 홈 페이지 애니메이션 효과 추가
  src/api/postUploadImage.js
  src/assets/images/img-01.svg
  src/assets/images/img-02.png
  src/assets/images/img_02.png
  src/components/UserProfileSelector/UserProfileSelector.jsx
  src/components/UserProfileSelector/UserProfileSelector.module.scss
  src/components/common/Button.module.scss
  src/pages/Home/Home.jsx
  src/pages/Home/Home.module.scss
Labels: ✨ 기능 추가/구현, 📁 폴더구조 변경

#90 🎨 style: HeaderService 레이아웃 및 반응형 디자인 개선
  src/components/UserProfileSelector/UserProfileSelector.jsx
  src/components/recipient/HeaderService/HeaderService.jsx
  src/components/recipient/HeaderService/HeaderService.module.scss
  src/components/recipient/HeaderService/Share/ShareButton.module.scss
  src/utils/share.js
Labels: 🐛 버그 수정, ✨ 기능 추가/구현, 🎨 UI/스타일 관련

#91 🎨 style: 반응형 기준 수정 (1024px -> 1023px , 768px -> 767px)
  src/components/Card/Card.module.scss
  src/components/Modal/Modal.module.scss
  src/pages/CreateRecipient/CreateRecipient.module.scss
  src/pages/Recipient/Recipient.module.scss
Labels: 🎨 UI/스타일 관련

#96 ♻️ refactor: 버튼 여백 조정 및 프로필 이미지 높이 추가
  src/components/UserProfileSelector/UserProfileSelector.module.scss
  src/components/common/Button.module.scss
  src/pages/RecipientList/RecipientList.module.scss
Labels: ♻️ 리팩토링

#104 배경 이미지 추가 기능 구현, 애니메이션 추가, 코드 refactoring
  src/assets/images/upload.svg
  src/components/BackgroundCard/BackgroundCard.jsx
  src/components/BackgroundCard/BackgroundCard.module.scss
  src/components/Card/Card.jsx
  src/components/Card/Card.module.scss
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.module.scss
  src/pages/CreateRecipient/CreateRecipient.jsx
  src/pages/CreateRecipient/CreateRecipient.module.scss
Labels: ✨ 기능 추가/구현, 🎨 UI/스타일 관련, ♻️ 리팩토링

#107 🎨 style: 뒤로가기 버튼 색상 조정
  index.html
  src/pages/Recipient/Recipient.module.scss
Labels: 🎨 UI/스타일 관련

#113 ✨ feat: 이모지 리액션 옵티미스틱 UI 적용 및 드래그 방지
  src/components/FontSelect/FontSelect.jsx
  src/components/recipient/HeaderService/HeaderService.jsx
  src/components/recipient/HeaderService/HeaderService.module.scss
Labels: ✨ 기능 추가/구현, 🎨 UI/스타일 관련

#114 🐛 fix: 메시지 전송 중복 방지를 위한 상태 관리 추가
  src/pages/CreateRecipient/CreateRecipient.jsx
  src/pages/MessageForm/MessageForm.jsx
Labels: 🐛 버그 수정

#115 🔧 chore: CI/CD 파이프라인 구축 및 빌드 테스트 추가
  .github/workflows/sync-fork.yml
Labels: 🔧 설정/환경 변경, 🚀 배포 관련
